<a href="https://colab.research.google.com/github/rajabi-j/ML_Practice/blob/main/NumPy_Practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import of libraries

In [ ]:
import numpy as np

np.__version__

'1.21.6'

### np.all()

Test whether all array elements along a given axis evaluate to True.

Check if all array elements $ A, B, C $ and $ D $ return the logical value _True_.

```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])
```

In [ ]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.all(array)}')

A: True
B: False
C: False
D: True


### np.all() with the parameter axis

Check if all array elements $ A, B $ and $ C $ return the logical value _True_ along the axis with index 1.

```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])
```

In [ ]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

for name, array in zip(list('ABC'), [A, B, C]):
    print(f'{name}: {np.all(array, axis=1)}')

A: [ True  True]
B: [ True False]
C: [False  True]


### np.any()

Test whether any array element along a given axis evaluates to True.

Check if any element of arrays $ A, B, C $ and $ D $ returns the logical value _True_.

```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```

In [ ]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.any(array)}')

A: False
B: True
C: True
D: True


### np.any() with the parameter axis

Check if any element of arrays $ A, B, C $ and $ D $ returns the logical value _True_ along the axis with index 0.

```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```

In [ ]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.any(array, axis=0)}')

A: [False False False]
B: [False  True False]
C: [ True False False]
D: [ True False]


### np.isnan() 

Test element-wise for NaN and return result as a boolean array.

Check the array $ A $ for missing data (_np.nan_).

```
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
```

In [ ]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

np.isnan(A)

array([[False, False, False,  True],
       [False,  True, False, False]])

### np.allclose()

Returns True if two arrays are element-wise equal within a tolerance.

Check if the following arrays $ A $ and $ B $ are equal in terms of elements (element-wise) with the specified tolerance level. Use the _np.allclose()_ function with default parameters.

```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])
```

In [ ]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

np.allclose(A, B)

True

### == and np.equal()

Check if the following arrays $ A $ and $ B $ are equal in terms of elements (element-wise). Use the comparison operator _==_.

```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])
```

In [ ]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

# Solution 1
A == B

array([False, False,  True])

In [ ]:
# Solution 2
np.equal(A, B)

array([False, False,  True])

### > and np.greater()

Check which elements (element-wise) from the array $ A $ below have higher values than the array $ B $.

```
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
```

In [ ]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

# Solution 1
A > B

array([ True, False, False, False])

In [ ]:
# Solution 2
np.greater(A, B)

array([ True, False, False, False])

### np.zeros()

Return a new array of given shape and type, filled with zeros.

Create an array of numpy dimensions _4x4_ filled with zeros. Set the data type to _int_.

__Expected result:__

```
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
```

In [ ]:
np.zeros(shape=(4, 4), dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### np.ones() and np.full()

np.one() return a new array of given shape and type, filled with ones.

np.full() return a new array of given shape and type, filled with fill_value.

Create an array of numpy dimensions _4x6_ filled with number 255. Set the data type to _float_.

__Expected result:__
```
array([[255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255.]])
```

In [ ]:
# Solution 1
np.ones(shape=(4, 6), dtype='float') * 255

array([[255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255.]])

In [ ]:
# Solution 2
np.full(shape=(4, 6), fill_value=255, dtype='float')

array([[255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255.]])

### np.arange()

Return evenly spaced values within a given interval.

Build a one-dimensional numpy array of two-digit numbers from 10 to 30.

__Expected result:__
```
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])
```

In [ ]:
np.arange(10, 31)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

### np.ndarray.reshape()

Returns an array containing the same data with a new shape.

Build the numpy array specified below:

```
array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])
```

Note that the shape of the array is (4, 5).

In [ ]:
# Solution 1
np.arange(11, 31).reshape(-1, 5)

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
# Solution 2
np.arange(11, 31).reshape(4, 5)

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### np.eye()

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Build a _4x4_ two-dimensional array - identity matrix. Use the _int_ data type.

__Expected result:__

```
array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])
```

In [ ]:
np.eye(N=4, dtype='int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### np.random.rand()

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

Set the random seed to 10. Then build a one-dimensional array consisting of 20 pseudo-randomly generated values from the uniform distribution above the $ [0, 1) $ interval.

__Expected result:__

```
array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578])
```

In [ ]:
np.random.seed(10)
np.random.rand(20)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578])

### np.random.randn()

Return a sample (or samples) from the “standard normal” distribution.

Set the random seed to 20. Then build a two-dimensional array with the shape _(5, 4)_ pseudo-random values generated from the standard normal distribution $ N (0, 1) $.

__Expected result:__
```
array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843]])
```

In [ ]:
np.random.seed(20)
np.random.randn(5, 4)

array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843]])

### np.random.randn() with mean and sigma

Set the random seed to 30. Then build a two-dimensional array with the shape _(5, 4)_ pseudo-random values generated from the normal distribution $ N (100, 5) $.
$\mu=100$   
$\sigma^{2}=5$

__Expected result:__
```
array([[ 97.17349231, 103.41650023,  97.82942436, 101.05220329],
       [ 99.7748353 , 100.67930221,  96.14063068, 103.544381  ],
       [100.30029631,  97.52499594, 103.52901961, 100.24037271],
       [ 98.29153712,  98.2666258 , 103.09437633, 101.70027274],
       [ 99.36127721, 101.20382627,  95.34026547, 102.09694365]])
```

In [ ]:
np.random.seed(30)

sigma = np.sqrt(5)
mu = 100

sigma * np.random.randn(5, 4) + mu

array([[ 97.17349231, 103.41650023,  97.82942436, 101.05220329],
       [ 99.7748353 , 100.67930221,  96.14063068, 103.544381  ],
       [100.30029631,  97.52499594, 103.52901961, 100.24037271],
       [ 98.29153712,  98.2666258 , 103.09437633, 101.70027274],
       [ 99.36127721, 101.20382627,  95.34026547, 102.09694365]])

### np.nditer()

Efficient multi-dimensional iterator object to iterate over arrays.

Iterating by array numpy $ A $ element by element (element-wise) print each element of the array to the console.

```
A = np.array([[1, 4, 3],
              [5, 2, 6]])
```

In [ ]:
A = np.array([[1, 4, 3],
              [5, 2, 6]])

for i in np.nditer(A):
    print(i, end=" ")

1 4 3 5 2 6 

### np.linspace()

Returns num evenly spaced samples, calculated over the interval [start, stop].

Create a one-dimensional numpy array (vector) consisting of 6 equally spaced points from the interval $ [0, 1]. $

__Expected result:__
```
array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])
```

In [ ]:
np.linspace(start=0, stop=1, num=6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

### np.random.randint()

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

Set the random seed to 42. Generate a one-dimensional array (a 6-element vector) of values from 1 to 49 inclusive.

__Expected result:__
```
array([39, 29, 15, 43,  8, 21])
```

In [ ]:
np.random.seed(42)
np.random.randint(low=1, high=50, size=6)

array([39, 29, 15, 43,  8, 21])

### np.diag()

Extract a diagonal or construct a diagonal array.

Build the two-dimensional _5x5_ size array below:

```
array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])
```

In [ ]:
# Solution 1
np.diag(np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [ ]:
# Solution 2
np.diag([0, 1, 2, 3, 4, 5])

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])